In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable


# The Basics

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [18]:
b = np.array([[5.0,2.0,6.0],[2.0,7.0,9.0]])
print(b)

[[5. 2. 6.]
 [2. 7. 9.]]


In [6]:
# Get Dimension
a.ndim

1

In [20]:
# Get shape
b.shape

(2, 3)

In [21]:
# Get Type
b.dtype

dtype('float64')

In [22]:
# Get size
a.itemsize

4

In [23]:
# Get total size
a.size

3

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [row, column]
a[0,5]

6

In [26]:
a[1,-4]

11

In [27]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [29]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [30]:
a[0,1:-1:2]

array([2, 4, 6])

In [31]:
a[1,5] = 24
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 24 14]]


In [32]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 24 14]]


# *3-d example

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (work outside in)

In [36]:
b[0,1,1]

4

In [41]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [42]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [46]:
# Replace
b[:,0,:] = [[9,9],[8,8]]
b

array([[[9, 9],
        [3, 4]],

       [[8, 8],
        [7, 8]]])

# Initializing Different Types of Arrays

In [50]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [55]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
# All 1s matrix
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
np.ones((2,3,3), dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [63]:
# Any other number(shape, value)
np.full((2,2), 77)

array([[77, 77],
       [77, 77]])

In [68]:
# Any other number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [77]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.22040369, 0.6849389 ],
       [0.655645  , 0.39821775],
       [0.30994887, 0.13639278],
       [0.0887262 , 0.27870894]])

In [85]:
np.random.randint(8, size=(3,3))

array([[6, 5, 3],
       [6, 4, 3],
       [2, 7, 3]])

In [88]:
# The identity matrix
np.identity((5), dtype = 'int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [89]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [93]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# When copying array

In [15]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [24]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [25]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


# Mathematics

In [43]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [44]:
a+2

array([3, 4, 5, 6])

In [45]:
a-2

array([-1,  0,  1,  2])

In [46]:
a*2

array([2, 4, 6, 8])

In [47]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [48]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [49]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [50]:
a**2

array([ 1,  4,  9, 16])

In [51]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [53]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linear Algebra

In [58]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # Matrix Multiple function

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.min(stats)

1

In [62]:
np.max(stats)

6

In [65]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [66]:
np.min(stats, axis = 1)

array([1, 4])

In [67]:
np.sum(stats)

21

# Reorganizing Arrays

In [71]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [74]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [77]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [78]:
# Vertically stacking vectoes
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [82]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,4))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
h2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

# Miscellaneous

## Load Data from File

In [91]:
filedata = np.genfromtxt('data.txt', delimiter=',')
data = filedata.astype('int32')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [92]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [93]:
data[data>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [100]:
table = ([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
table

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25],
 [26, 27, 28, 29, 30]]